#ifndef OTSUGAUSSION_LIBRARY_GLOBAL_H
#define OTSUGAUSSION_LIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef OTSUGAUSSION_LIBRARY_LIB
# define OTSUGAUSSION_LIBRARY_EXPORT Q_DECL_EXPORT
#else
# define OTSUGAUSSION_LIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // OTSUGAUSSION_LIBRARY_GLOBAL_H
